//! DBML (Database Markup Language) export for schema visualization.
//!
//! DBML is a human-readable text format for defining database schemas.
//! This module converts a `SchemaGraph` to DBML text for export.

use petgraph::prelude::{DiGraph, EdgeRef};

use crate::graph::{SchemaGraph, TableNodeId};

/// DBML export scope.
#[derive(Clone, Copy, Debug)]
pub enum DbmlScope {
    /// Only the focal table and its immediate neighbors.
    FocalTable,
    /// The entire loaded subgraph (all tables currently in the graph).
    Subgraph,
    /// Full schema export (all tables, all relationships).
    FullSchema,
}

/// Convert a SchemaGraph to DBML text.
pub fn to_dbml(graph: &SchemaGraph, scope: DbmlScope) -> Result<String, String> {
    let export_graph = match scope {
        DbmlScope::FocalTable => {
            // For FocalTable, extract just the focal table + 1-hop neighbors.
            if let Some((_focal_idx, focal_node)) = graph.most_connected_node() {
                extract_focal_subgraph(graph, &focal_node.id.name, focal_node.id.schema.as_deref())
            } else {
                return build_dbml_text(graph);
            }
        }
        DbmlScope::Subgraph | DbmlScope::FullSchema => {
            return build_dbml_text(graph);
        }
    };

    build_dbml_text(&export_graph)
}

/// Build DBML text from a SchemaGraph.
fn build_dbml_text(graph: &SchemaGraph) -> Result<String, String> {
    let mut output = String::new();

    // DBML header comment
    output.push_str("// DBML generated by DBFlux\n\n");
    output.push_str("Project dbflux_export {\n");
    output.push_str("}\n\n");

    // Collect refs first so we can sort them
    let mut refs: Vec<String> = Vec::new();

    // Convert nodes to DBML tables
    for (node_idx, node) in graph.nodes() {
        output.push_str(&format!("Table {} {{\n", build_table_name(&node.id)));

        for col in &node.columns {
            let col_type = map_type_name(&col.type_name);
            let mut modifiers = Vec::new();

            if col.is_pk {
                modifiers.push("pk");
            }
            if col.type_name.to_lowercase().contains("serial")
                || col.type_name.to_lowercase().contains("autoincrement")
            {
                modifiers.push("increment");
            }
            // Nullable if not pk and not fk
            if !col.is_pk && !col.is_fk {
                modifiers.push("null");
            }

            let modifier_str = if modifiers.is_empty() {
                String::new()
            } else {
                format!(" [{}]", modifiers.join(", "))
            };

            output.push_str(&format!("  {} {}{}\n", col.name, col_type, modifier_str));
        }

        output.push_str("}\n\n");

        // Collect refs from edges where this node is the source
        for edge_idx in graph.edge_indices() {
            if let Some((source_idx, target_idx)) = graph.edge_endpoints(edge_idx) {
                if source_idx == node_idx {
                    if let Some(edge) = graph.edge_weight(edge_idx) {
                        if let Some(target_node) = graph.node_weight(target_idx) {
                            let from_col = edge.from_columns.first().cloned().unwrap_or_default();
                            let to_col = edge.to_columns.first().cloned().unwrap_or_default();

                            let from_table = build_table_name(&node.id);
                            let to_table = build_table_name(&target_node.id);

                            let mut ref_parts = format!(
                                "Ref: {}.{} > {}.{}",
                                from_table, from_col, to_table, to_col
                            );

                            if let Some(ref on_delete) = edge.on_delete {
                                ref_parts.push_str(&format!(" on_delete: {}", on_delete));
                            }
                            if let Some(ref on_update) = edge.on_update {
                                ref_parts.push_str(&format!(" on_update: {}", on_update));
                            }

                            refs.push(ref_parts);
                        }
                    }
                }
            }
        }
    }

    // Output refs
    for r#ref in refs {
        output.push_str(&format!("{}\n", r#ref));
    }

    Ok(output)
}

/// Extract focal table + 1-hop neighbors as a new SchemaGraph.
fn extract_focal_subgraph(
    graph: &SchemaGraph,
    focal_name: &str,
    focal_schema: Option<&str>,
) -> SchemaGraph {
    let focal_id = TableNodeId {
        schema: focal_schema.map(String::from),
        name: focal_name.to_string(),
    };

    let Some(&focal_idx) = graph.node_index_by_id.get(&focal_id) else {
        return SchemaGraph {
            graph: DiGraph::new(),
            node_index_by_id: Default::default(),
        };
    };

    // BFS to find all 1-hop neighbors
    let mut visited = std::collections::HashSet::new();
    visited.insert(focal_idx);

    // Outgoing edges (this table references others)
    for edge in graph
        .graph
        .edges_directed(focal_idx, petgraph::Direction::Outgoing)
    {
        visited.insert(edge.target());
    }

    // Incoming edges (others reference this table)
    for edge in graph
        .graph
        .edges_directed(focal_idx, petgraph::Direction::Incoming)
    {
        visited.insert(edge.source());
    }

    // Build a new graph with just those nodes
    let mut subgraph = DiGraph::with_capacity(visited.len(), visited.len());
    let mut new_index_by_old = std::collections::HashMap::new();

    // Sort for deterministic ordering
    let mut visited_vec: Vec<_> = visited.into_iter().collect();
    visited_vec.sort_by_key(|&idx| {
        graph
            .node_weight(idx)
            .map(|n| n.id.name.as_str())
            .unwrap_or("")
    });

    for old_idx in visited_vec {
        let node = graph
            .node_weight(old_idx)
            .expect("old_idx is from the same graph")
            .clone();
        let new_idx = subgraph.add_node(node);
        new_index_by_old.insert(old_idx, new_idx);
    }

    // Add edges where both ends are in visited
    for edge_idx in graph.graph.edge_indices() {
        let (source, target) = match graph.graph.edge_endpoints(edge_idx) {
            Some(ends) => ends,
            None => continue,
        };

        if new_index_by_old.contains_key(&source) && new_index_by_old.contains_key(&target) {
            let weight = graph
                .graph
                .edge_weight(edge_idx)
                .expect("edge is from the same graph")
                .clone();
            let new_source = *new_index_by_old.get(&source).expect("source was visited");
            let new_target = *new_index_by_old.get(&target).expect("target was visited");
            subgraph.add_edge(new_source, new_target, weight);
        }
    }

    let node_index_by_id = new_index_by_old
        .iter()
        .map(|(_old_idx, &new_idx)| {
            let node = subgraph
                .node_weight(new_idx)
                .expect("new_idx was added via add_node");
            (node.id.clone(), new_idx)
        })
        .collect();

    SchemaGraph {
        graph: subgraph,
        node_index_by_id,
    }
}

/// Build a fully-qualified table name (schema.table or just table).
fn build_table_name(id: &TableNodeId) -> String {
    match &id.schema {
        Some(schema) => format!("{}.{}", schema, id.name),
        None => id.name.clone(),
    }
}

/// Map database type names to DBML type names.
fn map_type_name(type_name: &str) -> String {
    let lower = type_name.to_lowercase();

    // Handle common type patterns
    if lower.contains("serial") || lower.contains("autoincrement") {
        return "integer".to_string();
    }

    if lower.starts_with("varchar")
        || lower.starts_with("varchar2")
        || lower == "text"
        || lower.starts_with("char")
    {
        return "varchar".to_string();
    }

    if lower == "integer"
        || lower == "bigint"
        || lower == "smallint"
        || lower == "int"
        || lower == "int2"
        || lower == "int4"
        || lower == "int8"
    {
        return "integer".to_string();
    }

    if lower == "boolean" || lower == "bool" {
        return "boolean".to_string();
    }

    if lower.contains("timestamp")
        || lower.contains("datetime")
        || lower.contains("date")
        || lower.contains("time")
        || lower.contains("interval")
    {
        return "timestamp".to_string();
    }

    if lower.starts_with("json") || lower == "jsonb" {
        return "json".to_string();
    }

    if lower == "bytea" || lower.starts_with("blob") || lower.starts_with("binary") {
        return "blob".to_string();
    }

    if lower.starts_with("numeric")
        || lower.starts_with("decimal")
        || lower == "real"
        || lower == "double precision"
        || lower.starts_with("float")
    {
        return "numeric".to_string();
    }

    if lower == "uuid" {
        return "uuid".to_string();
    }

    // Return the original lowercased if no mapping
    lower
}

#[cfg(test)]
mod tests {
    use super::*;
    use dbflux_core::{ColumnInfo, ForeignKeyInfo, TableInfo};

    fn make_column(name: &str, type_name: &str, is_pk: bool) -> ColumnInfo {
        ColumnInfo {
            name: name.to_string(),
            type_name: type_name.to_string(),
            nullable: !is_pk,
            is_primary_key: is_pk,
            default_value: None,
            enum_values: None,
        }
    }

    fn make_fk(name: &str, from: Vec<&str>, to_table: &str, to_cols: Vec<&str>) -> ForeignKeyInfo {
        ForeignKeyInfo {
            name: name.to_string(),
            columns: from.into_iter().map(String::from).collect(),
            referenced_table: to_table.to_string(),
            referenced_schema: None,
            referenced_columns: to_cols.into_iter().map(String::from).collect(),
            on_delete: None,
            on_update: None,
        }
    }

    fn make_table(name: &str, columns: Vec<ColumnInfo>, fks: Vec<ForeignKeyInfo>) -> TableInfo {
        TableInfo {
            name: name.to_string(),
            schema: None,
            columns: Some(columns),
            indexes: None,
            foreign_keys: if fks.is_empty() { None } else { Some(fks) },
            constraints: None,
            sample_fields: None,
        }
    }

    #[test]
    fn test_dbml_basic() {
        let users = make_table(
            "users",
            vec![
                make_column("id", "serial", true),
                make_column("email", "varchar", false),
                make_column("created_at", "timestamp", false),
            ],
            vec![],
        );

        let graph = SchemaGraph::build(&[users]);
        let dbml = to_dbml(&graph, DbmlScope::Subgraph).expect("DBML export should succeed");

        // Verify basic structure
        assert!(dbml.contains("Table users {"));
        assert!(dbml.contains("  id integer [pk, increment]"));
        assert!(dbml.contains("  email varchar [null]"));
        assert!(dbml.contains("  created_at timestamp [null]"));
    }

    #[test]
    fn test_dbml_with_fk() {
        let users = make_table(
            "users",
            vec![
                make_column("id", "serial", true),
                make_column("email", "varchar", false),
            ],
            vec![],
        );

        let posts = make_table(
            "posts",
            vec![
                make_column("id", "serial", true),
                make_column("user_id", "integer", false),
                make_column("title", "varchar", false),
            ],
            vec![make_fk(
                "fk_posts_users",
                vec!["user_id"],
                "users",
                vec!["id"],
            )],
        );

        let graph = SchemaGraph::build(&[users, posts]);
        let dbml = to_dbml(&graph, DbmlScope::Subgraph).expect("DBML export should succeed");

        // Verify tables exist
        assert!(dbml.contains("Table users {"));
        assert!(dbml.contains("Table posts {"));

        // Verify FK reference
        assert!(dbml.contains("Ref: posts.user_id > users.id"));
    }

    #[test]
    fn test_dbml_valid_parseable() {
        let users = make_table(
            "users",
            vec![
                make_column("id", "serial", true),
                make_column("email", "varchar", false),
            ],
            vec![],
        );

        let posts = make_table(
            "posts",
            vec![
                make_column("id", "serial", true),
                make_column("user_id", "integer", false),
                make_column("title", "varchar", false),
            ],
            vec![make_fk(
                "fk_posts_users",
                vec!["user_id"],
                "users",
                vec!["id"],
            )],
        );

        let graph = SchemaGraph::build(&[users, posts]);
        let dbml = to_dbml(&graph, DbmlScope::Subgraph).expect("DBML export should succeed");

        // Verify the DBML can be parsed back (validates syntax)
        let parsed = dbml_rs::parse_dbml(&dbml);
        assert!(
            parsed.is_ok(),
            "Generated DBML should be parseable. Error: {:?}\n\nDBML:\n{}",
            parsed.err(),
            dbml
        );
    }

    #[test]
    fn test_dbml_with_schema() {
        let table = make_table("users", vec![make_column("id", "serial", true)], vec![]);

        let graph = SchemaGraph::build(&[TableInfo {
            schema: Some("public".to_string()),
            ..table
        }]);

        let dbml = to_dbml(&graph, DbmlScope::Subgraph).expect("DBML export should succeed");

        // Verify schema-qualified table name
        assert!(dbml.contains("Table public.users {"));
    }

    #[test]
    fn test_dbml_type_mapping() {
        let table = make_table(
            "test_types",
            vec![
                make_column("id", "BIGSERIAL", true),
                make_column("name", "VARCHAR(255)", false),
                make_column("active", "BOOLEAN", false),
                make_column("created", "TIMESTAMPTZ", false),
                make_column("data", "JSONB", false),
                make_column("balance", "NUMERIC(10,2)", false),
            ],
            vec![],
        );

        let graph = SchemaGraph::build(&[table]);
        let dbml = to_dbml(&graph, DbmlScope::Subgraph).expect("DBML export should succeed");

        // Verify type mappings
        assert!(dbml.contains("  id integer [pk, increment]"));
        assert!(dbml.contains("  name varchar [null]"));
        assert!(dbml.contains("  active boolean [null]"));
        assert!(dbml.contains("  created timestamp [null]"));
        assert!(dbml.contains("  data json [null]"));
        assert!(dbml.contains("  balance numeric [null]"));
    }

    #[test]
    fn test_dbml_focal_scope() {
        // Build a chain: a -> b -> c
        let a = make_table(
            "a",
            vec![make_column("id", "serial", true)],
            vec![make_fk("fk_a_b", vec!["id"], "b", vec!["id"])],
        );
        let b = make_table(
            "b",
            vec![make_column("id", "serial", true)],
            vec![make_fk("fk_b_c", vec!["id"], "c", vec!["id"])],
        );
        let c = make_table("c", vec![make_column("id", "serial", true)], vec![]);

        let graph = SchemaGraph::build(&[a, b, c]);

        // With FocalTable scope, should only get the focal node (b) and its neighbors (a, c)
        let dbml = to_dbml(&graph, DbmlScope::FocalTable).expect("DBML export should succeed");

        // Should contain all three tables since they're all 1-hop from b
        assert!(dbml.contains("Table a {"));
        assert!(dbml.contains("Table b {"));
        assert!(dbml.contains("Table c {"));
    }

    #[test]
    fn test_dbml_composite_fk() {
        let orders = make_table(
            "orders",
            vec![
                make_column("id", "integer", true),
                make_column("line_seq", "integer", true),
            ],
            vec![],
        );

        let line_items = make_table(
            "line_items",
            vec![
                make_column("order_id", "integer", false),
                make_column("line_id", "integer", false),
                make_column("qty", "integer", false),
            ],
            vec![ForeignKeyInfo {
                name: "fk_line_orders".into(),
                columns: vec!["order_id".into(), "line_id".into()],
                referenced_table: "orders".into(),
                referenced_schema: None,
                referenced_columns: vec!["id".into(), "line_seq".into()],
                on_delete: Some("CASCADE".into()),
                on_update: None,
            }],
        );

        let graph = SchemaGraph::build(&[orders, line_items]);
        let dbml = to_dbml(&graph, DbmlScope::Subgraph).expect("DBML export should succeed");

        // Verify composite FK is represented
        assert!(dbml.contains("Ref: line_items.order_id > orders.id"));
        assert!(dbml.contains("on_delete: CASCADE"));
    }

    #[test]
    fn test_dbml_empty_graph() {
        let graph = SchemaGraph::build(&[]);
        let dbml = to_dbml(&graph, DbmlScope::Subgraph).expect("DBML export should succeed");

        // Empty graph should still produce header
        assert!(dbml.contains("Project"));
    }
}
